services:
  web:
    build: ./
    command: uv run manage.py runserver --settings=kmm_web_backend.settings.local
    volumes:
      - ./app./:/kmm-web
    ports:
      - "8000:8000"
    env_file:
      - ./.env